# Generated by Django 3.0 on 2022-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='topic',
            field=models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('ruby', 'Ruby'), ('golang', 'Golang'), ('sql', 'SQL'), ('swift', 'Swift'), ('php', 'PHP'), ('delphi', 'Delphi'), ('perl', 'Perl')], default='python', max_length=20, verbose_name='предмет'),
        ),
    ]
